[repository]
name = "hyprexpo2"
authors = ["Vaxry", "antonkesy"]
commit_pins = []

[hyprexpo2]
description = "A fork of the plugin hyprexpo with added workspace selection"
authors = ["Vaxry", "antonkesy"]
output = "hyprexpo2.so"
build = [
    "make all",
]
since_hyprland = 4364
